spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    username: root
    password: ehdmsdb9!

#application.properties ? ?? ??? ?? ??
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=ehdmsdb9!
#spring.datasource.url=jdbc:mysql://localhost:3306/board
